"""unique constraint agencies

Revision ID: 14613a906785
Revises: b3cac514aa69
Create Date: 2026-09-08 16:18:51.543885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14613a906785'
down_revision: Union[str, Sequence[str], None] = 'b3cac514aa69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_agencies_name_email', 'agencies', ['name', 'email'])
    op.create_unique_constraint('uq_agencies_name_lat_long', 'agencies', ['name', 'latitude', 'longitude'])
    op.create_unique_constraint('uq_agencies_name_phone', 'agencies', ['name', 'phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_agencies_name_phone', 'agencies', type_='unique')
    op.drop_constraint('uq_agencies_name_lat_long', 'agencies', type_='unique')
    op.drop_constraint('uq_agencies_name_email', 'agencies', type_='unique')
    # ### end Alembic commands ###
