"""create unique constraints

Revision ID: 19c960f6d088
Revises: 08dadd909515
Create Date: 2026-09-12 13:32:34.647494

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "19c960f6d088"
down_revision: Union[str, Sequence[str], None] = "08dadd909515"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "agencies", ["id"])
    op.create_unique_constraint(None, "incident_media", ["id"])
    op.create_unique_constraint(None, "incidents", ["id"])
    op.create_unique_constraint(None, "medic_profile", ["id"])
    op.create_unique_constraint(None, "notifications", ["id"])
    op.create_unique_constraint(None, "revoked_tokens", ["id"])
    op.create_unique_constraint(None, "roles", ["id"])
    op.create_unique_constraint(None, "sos", ["id"])
    op.create_unique_constraint(None, "status_history", ["id"])
    op.create_unique_constraint(None, "user_devices", ["id"])
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "user_devices", type_="unique")
    op.drop_constraint(None, "status_history", type_="unique")
    op.drop_constraint(None, "sos", type_="unique")
    op.drop_constraint(None, "roles", type_="unique")
    op.drop_constraint(None, "revoked_tokens", type_="unique")
    op.drop_constraint(None, "notifications", type_="unique")
    op.drop_constraint(None, "medic_profile", type_="unique")
    op.drop_constraint(None, "incidents", type_="unique")
    op.drop_constraint(None, "incident_media", type_="unique")
    op.drop_constraint(None, "agencies", type_="unique")
    # ### end Alembic commands ###
