"""notifications table, device tokens table, some other modifications in other tables

Revision ID: 1cc35067e683
Revises: 663f141f930a
Create Date: 2026-08-31 15:30:36.246424

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.

revision: str = "1cc35067e683"

down_revision: Union[str, Sequence[str], None] = "663f141f930a"

branch_labels: Union[str, Sequence[str], None] = None

depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    report_summary_enum = postgresql.ENUM(
        "FIRE",
        "ACCIDENT",
        "CRIME",
        name="report_summary_enum",
    )

    report_summary_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "user_devices",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "owner_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "device_token",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "platform",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_token"),
        sa.UniqueConstraint("id"),
    )

    op.create_table(
        "notifications",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "incident_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum(
                "PUSH",
                "SMS",
                "WHATSAPP",
                name="notification_channel_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SENT",
                "FAILED",
                name="notification_status_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "recipient_email",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "recipient_phone",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "title",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "message",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "sent_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "error",
            sa.String(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["reports.id"],
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )

    op.add_column(
        "reports",
        sa.Column(
            "report_summary",
            sa.Enum(
                "FIRE",
                "ACCIDENT",
                "CRIME",
                name="report_summary_enum",
            ),
            nullable=True,
        ),
    )

    op.create_unique_constraint(
        None,
        "revoked_tokens",
        ["id"],
    )

    op.add_column(
        "sos",
        sa.Column(
            "email",
            sa.String(),
            nullable=True,
        ),
    )

    op.create_unique_constraint(
        "uq_sos_owner_email",
        "sos",
        ["owner_id", "email"],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
        "uq_sos_owner_email",
        "sos",
        type_="unique",
    )

    op.drop_column(
        "sos",
        "email",
    )

    op.drop_column(
        "reports",
        "report_summary",
    )

    op.drop_table(
        "notifications",
    )

    op.drop_table(
        "user_devices",
    )

    op.execute("""
        ALTER TABLE revoked_tokens
        DROP CONSTRAINT IF EXISTS revoked_tokens_id_key
    """)

    op.execute("""
        DROP TYPE IF EXISTS notification_channel_enum
    """)

    op.execute("""
        DROP TYPE IF EXISTS notification_status_enum
    """)

    op.execute("""
        DROP TYPE IF EXISTS report_summary_enum
    """)

    # ### end Alembic commands ###
