"""users org_id foreign key

Revision ID: 33adfaa010c1
Revises: e31a01075cc7
Create Date: 2026-08-27 20:07:51.458881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33adfaa010c1'
down_revision: Union[str, Sequence[str], None] = 'e31a01075cc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'users', 'agencies', ['org_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
