"""use object_key and content_type in media and remove url

Revision ID: 4224f0718102
Revises: 33adfaa010c1
Create Date: 2026-08-28 12:24:15.580376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4224f0718102'
down_revision: Union[str, Sequence[str], None] = '33adfaa010c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_media', sa.Column('object_key', sa.String(), nullable=False))
    op.add_column('incident_media', sa.Column('content_type', sa.String(), nullable=False))
    op.drop_column('incident_media', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_media', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('incident_media', 'content_type')
    op.drop_column('incident_media', 'object_key')
    # ### end Alembic commands ###
