"""agency_name to name in agencies table

Revision ID: 547600781c7a
Revises: e30930031bae
Create Date: 2026-08-23 03:00:25.970457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547600781c7a'
down_revision: Union[str, Sequence[str], None] = 'e30930031bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agencies', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint(op.f('agencies_agency_name_key'), 'agencies', type_='unique')
    op.create_unique_constraint(None, 'agencies', ['name'])
    op.drop_column('agencies', 'agency_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agencies', sa.Column('agency_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'agencies', type_='unique')
    op.create_unique_constraint(op.f('agencies_agency_name_key'), 'agencies', ['agency_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('agencies', 'name')
    # ### end Alembic commands ###
