"""add agency_id to reports table

Revision ID: 601493ef6854
Revises: 14613a906785
Create Date: 2026-09-08 17:03:06.693604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '601493ef6854'
down_revision: Union[str, Sequence[str], None] = '14613a906785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('agency_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'reports', 'agencies', ['agency_id'], ['id'], ondelete='set null')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'agency_id')
    # ### end Alembic commands ###
