"""add upload status in media

Revision ID: 7eed187443aa
Revises: 4224f0718102
Create Date: 2026-08-28 12:53:38.996202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eed187443aa'
down_revision: Union[str, Sequence[str], None] = '4224f0718102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_media', sa.Column('upload_status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident_media', 'upload_status')
    # ### end Alembic commands ###
