"""set phone in sos to unique

Revision ID: 89b56736377a
Revises: f9cca34e7793
Create Date: 2026-08-13 00:26:18.610452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b56736377a'
down_revision: Union[str, Sequence[str], None] = 'f9cca34e7793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sos', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sos', type_='unique')
    # ### end Alembic commands ###
