"""Add password column to users table

Revision ID: 976116f5c7bd
Revises: e3a6d4cf563f
Create Date: 2026-07-28 22:44:20.487937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976116f5c7bd'
down_revision: Union[str, Sequence[str], None] = 'e3a6d4cf563f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'agencies', ['id'])
    op.create_unique_constraint(None, 'incident_media', ['id'])
    op.create_unique_constraint(None, 'medic_profile', ['id'])
    op.create_unique_constraint(None, 'reports', ['id'])
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'sos', ['id'])
    op.create_unique_constraint(None, 'status_history', ['id'])
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'password')
    op.drop_constraint(None, 'status_history', type_='unique')
    op.drop_constraint(None, 'sos', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'reports', type_='unique')
    op.drop_constraint(None, 'medic_profile', type_='unique')
    op.drop_constraint(None, 'incident_media', type_='unique')
    op.drop_constraint(None, 'agencies', type_='unique')
    # ### end Alembic commands ###
