"""unique user devices

Revision ID: 97f44f92884b
Revises: c8d2268fd060
Create Date: 2026-09-12 17:02:07.122704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f44f92884b'
down_revision: Union[str, Sequence[str], None] = 'c8d2268fd060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_devices', ['owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_devices', type_='unique')
    # ### end Alembic commands ###
