"""notification retry count

Revision ID: b3cac514aa69
Revises: 1cc35067e683
Create Date: 2026-09-08 13:43:57.119791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3cac514aa69'
down_revision: Union[str, Sequence[str], None] = '1cc35067e683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.create_unique_constraint(None, 'notifications', ['id'])
    op.create_unique_constraint(None, 'user_devices', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_devices', type_='unique')
    op.drop_constraint(None, 'notifications', type_='unique')
    op.drop_column('notifications', 'retry_count')
    # ### end Alembic commands ###
