"""change not null to null in users org_id

Revision ID: c8d2268fd060
Revises: 2ec0448d55c8
Create Date: 2026-09-12 16:38:42.301249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8d2268fd060'
down_revision: Union[str, Sequence[str], None] = '2ec0448d55c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
