"""changed org_type in agencies table to enum

Revision ID: e30930031bae
Revises: ecb2c16c36c2
Create Date: 2026-08-23 02:33:33.027732

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e30930031bae"
down_revision: Union[str, Sequence[str], None] = "ecb2c16c36c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

org_type_enum = postgresql.ENUM(
    "MEDICAL",
    "FIRE_SERVICE",
    "LAW",
    name="org_type_enum",
)


def upgrade() -> None:
    """Upgrade schema."""

    org_type_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        "agencies",
        "org_type",
        existing_type=sa.VARCHAR(),
        type_=org_type_enum,
        existing_nullable=False,
        postgresql_using="org_type::org_type_enum",
    ),
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agencies",
        "org_type",
        existing_type=org_type_enum,
        type_=sa.VARCHAR(),
        existing_nullable=False,
        postgresql_using="org_type::text",
    ),
    # ### end Alembic commands ###
