"""linking admin users to organization

Revision ID: e31a01075cc7
Revises: 547600781c7a
Create Date: 2026-08-27 18:32:25.532480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e31a01075cc7'
down_revision: Union[str, Sequence[str], None] = '547600781c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'users', ['org_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'org_id')
    # ### end Alembic commands ###
