from app.agencies import models
from app.auth import models
from app.devices import models
from app.medic import models
from app.notifications import models
from app.reports import models
from app.roles import models
from app.sos import models
from app.status import models
from app.users import models
